Junit testing
wolox-training/adc-java pull request #13
Opened 2020-11-25 19:55 UTC by alexdavcudriz

## Summary
- Controllers testing was created.
- Repositories testieng was created.
## Trello Card
https://trello.com/c/1NNpqbY9/28-junit-testing

2020-11-25 20:06 UTC, facucompe requested changes
Amazing work!!

2020-11-25 20:06 UTC, facucompe commented on src/test/java/wolox/training/controllers/BookControllerTest.java
> +                .andExpect(jsonPath("[0].subtitle").value(bookTest.getSubtitle()));
```
.andExpect(content().json(objectMapper.writeValueAsString(bookTest)))
```

2020-11-25 20:06 UTC, facucompe commented on src/test/java/wolox/training/controllers/BookControllerTest.java
> +}
```suggestion
}

```

2020-11-25 20:06 UTC, facucompe commented on src/test/java/wolox/training/controllers/BookControllerTest.java
> +class BookControllerTest {
What about not found cases

2020-11-25 20:06 UTC, facucompe commented on src/test/java/wolox/training/repositories/BookRepositoryTest.java
> +}
```suggestion
}

```

2020-11-26 19:28 UTC, facucompe approved these changes

2020-11-26 21:33 UTC, jdhiguita approved these changes

2020-11-27 14:02 UTC, merged