Spring security
wolox-training/adc-java pull request #14
Opened 2020-11-25 22:10 UTC by alexdavcudriz

## Summary
- SecurityConfig was created.
- AuthenticationProvider was created.
- Password field was added in User model.
- PasswordEncoder was implement in create User endpoint.
## Trello Card
https://trello.com/c/J3Xv1CpG/23-integrar-spring-security

2020-11-27 16:12 UTC, facucompe requested changes

2020-11-27 16:12 UTC, facucompe commented on src/main/java/wolox/training/security/AuthenticationProvider.java
> +        return new User(userFound.getUsername(), userFound.getPassword(), Collections.emptyList());
```
return userRepository.findByUsername()
    .map(userFound -> new User(userFound.getUsername(), userFound.getPassword(), Collections.emptyList()))
    .orElseThrow(() -> new UsernameNotFoundException("User not found"));
```

2020-11-27 16:12 UTC, facucompe commented on src/test/java/wolox/training/controllers/UserControllerTest.java
> +    @Test
Don't you need to use `@WithMockUser` now that we have authentication?

2020-12-01 15:51 UTC, facucompe approved these changes

2020-12-01 15:51 UTC, facucompe commented on src/main/java/wolox/training/models/PasswordReset.java
> +}
Settings → Editor → General → Ensure line feed at file end on Save
```suggestion
}

```

2020-12-01 15:59 UTC, facucompe approved these changes

2020-12-02 16:23 UTC, jdhiguita approved these changes

2020-12-04 13:41 UTC, merged