External api integration
wolox-training/adc-java pull request #15
Opened 2020-11-26 16:11 UTC by alexdavcudriz

## Summary
- Feign configuration was added.
- Client models was created.
- Client delegates was created.
- Isbn search was added.
## Trello Card
https://trello.com/c/oktaL917/22-integraci%C3%B3n-api-externa

2020-11-26 22:09 UTC, facucompe requested changes
What about Service test? We will see web mocks later to test OpenLibrary Component Test

2020-11-26 22:09 UTC, facucompe commented on src/main/java/wolox/training/client/delegate/OpenLibraryDelegate.java
> +        return Optional.empty();
I don't like the Optional ofNullable inside a if

2020-11-26 22:09 UTC, facucompe commented on src/main/java/wolox/training/client/delegate/OpenLibraryDelegate.java
> +        return Optional.empty();
Maybe this works as well:
```
return Optional.ofNullable(bookInfoResponse.get(isbnParam.toString()))
    .map(bookInfo -> objectMapper.convertValue(bookInfo, BookInfoDto.class));
```

2020-11-26 22:09 UTC, facucompe commented on src/main/java/wolox/training/services/BookService.java
> +        return Collections.singleton(bookRepository.save(bookFound));
Same here. If you use optional try not asking if it's present.

2020-11-26 22:09 UTC, facucompe commented on src/main/java/wolox/training/services/BookService.java
> +        return Collections.singleton(bookRepository.save(bookFound));
```
return bookRepository.findByIsbn(isbn)
     .map(book -> Collections.singleton(book))
     .orElse(openLibraryBook(isbn));
```

2020-12-01 15:59 UTC, facucompe approved these changes

2020-12-02 16:25 UTC, jdhiguita approved these changes

2020-12-04 13:42 UTC, merged