Get logged in user
wolox-training/adc-java pull request #16
Opened 2020-11-26 16:45 UTC by alexdavcudriz

## Summary
- SpringContextAuthentication was created.
- IAuthentication was created.
- authenticatedCurrentUser method was created.
## Trello Card
https://trello.com/c/C0tYhgBB/27-acceder-a-la-informaci%C3%B3n-del-user-logueado

2020-11-27 16:11 UTC, facucompe requested changes

2020-11-27 16:11 UTC, facucompe commented on src/main/java/wolox/training/controllers/UserController.java
> +    public String authenticatedCurrentUser() {
Return a JSON object, do not return a plain text

2020-12-01 18:00 UTC, facucompe approved these changes

2020-12-02 16:26 UTC, jdhiguita approved these changes

2020-12-04 13:44 UTC, merged